In [ ]:
import pandas as pd
from google.colab import drive
from google.colab.patches import cv2_imshow

import cv2
import os
import numpy as np
from keras.utils import np_utils
from keras.models import Sequential
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from keras.layers import *
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.preprocessing import image
import pickle

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
food_list=os.listdir('/content/drive/MyDrive/final_project/food_img')

In [ ]:
food_list.remove('test')

In [ ]:
food_list

['01015013',
 '12011008',
 '01011001',
 '01015010',
 '04016001 validation ',
 '04016001']

In [ ]:
food_list.remove('04016001 validation ')

In [ ]:
food_list

['01015013', '12011008', '01011001', '01015010', '04016001']

In [ ]:
from PIL import ImageFile 
ImageFile.LOAD_TRUNCATED_IMAGES = True

In [ ]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
food_list

['01015013', '12011008', '01011001', '01015010', '04016001']

In [ ]:
# label = [food_list[1]]

In [ ]:
def imageprocessing(food_list):
  train = []
  test = []
  for idx, j in enumerate(food_list):
    label = food_list[idx]
    # label = [0 for i in range(len(food_list))]
    # label[idx] = food_list[idx] or 1
    pro_food = os.listdir('/content/drive/MyDrive/final_project/food_img/'+j)
    for k in pro_food:
      img =load_img('/content/drive/MyDrive/final_project/food_img/'+j+'/'+k, target_size=(128,128))
      img = img.convert("RGB")
      imgArray = np.uint8(image.img_to_array(img)) / 255.0
      train.append(imgArray)
      test.append(label)
  img_Array = np.array(train)
  img_label = test
  # img_label = np.array(test)
  with open('./drive/MyDrive/final_project/pickle/x_pickle/food.pickle', 'wb') as f:
    pickle.dump(img_Array, f, pickle.HIGHEST_PROTOCOL)
  with open('./drive/MyDrive/final_project/pickle/y_pickle/food_label1.pickle', 'wb') as f:
    pickle.dump(img_label, f, pickle.HIGHEST_PROTOCOL)

In [ ]:
imageprocessing(food_list)

In [ ]:
with open('food.pickle', 'rb') as f:
    data = pickle.load(f)

print(data)

[[[[0.73333333 0.56078431 0.41568627]
   [0.74117647 0.56862745 0.42352941]
   [0.75686275 0.58431373 0.43137255]
   ...
   [0.68627451 0.52156863 0.36470588]
   [0.69411765 0.52941176 0.37254902]
   [0.68627451 0.51372549 0.36862745]]

  [[0.7254902  0.55294118 0.40784314]
   [0.70980392 0.5372549  0.39215686]
   [0.73333333 0.56078431 0.40784314]
   ...
   [0.69019608 0.5254902  0.36862745]
   [0.69019608 0.5254902  0.36862745]
   [0.68235294 0.50980392 0.36470588]]

  [[0.71764706 0.54509804 0.40784314]
   [0.71764706 0.54509804 0.40784314]
   [0.7254902  0.55294118 0.41568627]
   ...
   [0.69411765 0.52941176 0.38039216]
   [0.69019608 0.5254902  0.36862745]
   [0.67058824 0.49803922 0.35294118]]

  ...

  [[0.68235294 0.52156863 0.40392157]
   [0.67843137 0.51764706 0.4       ]
   [0.62745098 0.46666667 0.34901961]
   ...
   [0.43137255 0.30196078 0.18039216]
   [0.39607843 0.26666667 0.14509804]
   [0.4        0.27058824 0.14901961]]

  [[0.68627451 0.5254902  0.40784314]
   [0.6

In [ ]:
with open('food_label.pickle', 'rb') as f:
    data1 = pickle.load(f)

print(data1)

[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 ...
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]]


In [ ]:
with open('food_label.pickle', 'rb') as f:
    data1 = pickle.load(f)

print(data1)

[['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013'

In [ ]:
with open('food_label1.pickle', 'rb') as f:
    data1 = pickle.load(f)

print(data1)

[['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013', 0, 0, 0, 0], ['01015013'